version: "2"
services:
  app:
      volumes:
         - .:/var/www/html:rw
  mysql:
      environment:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: margaron
          MYSQL_USER: margaron
          MYSQL_PASSWORD: margaron
